{{- if and .Values.ssh.enabled .Values.ssh.ca .Values.ssh.ca.vault .Values.ssh.ca.vault.auth (not .Values.ssh.ca.vault.auth.existingTokenSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.sshVaultTokenSecretName" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ required "ssh.ca.vault.auth.token is required" .Values.ssh.ca.vault.auth.token | b64enc }}
{{- end }}
