{{- if and .Values.ssh.enabled .Values.ssh.ca .Values.ssh.ca.manual (not .Values.ssh.ca.manual.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.sshManualCASecretName" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  ca-private-key: {{ required "ssh.ca.manual.privateKey is required" .Values.ssh.ca.manual.privateKey | b64enc }}
{{- end }}
