{{- if and .Values.ssh.enabled .Values.ssh.ca .Values.ssh.ca.vault .Values.ssh.ca.vault.caBundle (not .Values.ssh.ca.vault.existingCABundleSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.sshVaultCABundleSecretName" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.ssh.ca.vault.caBundle | b64enc }}
{{- end }}
